#Basic Data Exploration and Cleaning using Pandas

## Objective

The objective of this assignment is to perform basic data exploration and cleaning operations using the Pandas Library in Python.

Operations Performed: 

    Loading CSV dataset

    Exploring dataset Structure

    Handling missing values

    Filtering and selecting data

    Removing duplicate records

    Creating derived columns 

    Saving cleaned dataset

In [76]:
import pandas as pd

In [77]:
csv_1 = pd.read_csv("Combined_dataset.csv")

In [78]:
csv_1.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [79]:
print(f"Shape: {csv_1.shape}")

Shape: (1000, 24)

In [80]:
csv_1.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [81]:
print(f"\nDataset Shape: {csv_1.shape[0]} rows x {csv_1.shape[1]} columns")

Dataset Shape: 1000 rows x 24 columns

In [82]:
csv_1.columns.tolist()

['product_id',
 'title',
 'product_description',
 'rating',
 'ratings_count',
 'initial_price',
 'discount',
 'final_price',
 'currency',
 'images',
 'delivery_options',
 'product_details',
 'breadcrumbs',
 'product_specifications',
 'amount_of_stars',
 'what_customers_said',
 'seller_name',
 'sizes',
 'videos',
 'seller_information',
 'variations',
 'best_offer',
 'more_offers',
 'category']

In [83]:
csv_1.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [84]:
csv_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [85]:
csv_1.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [86]:
# Step 1 — First identify missing values BEFORE filling
print("Missing values per column:")
print(csv_1.isnull().sum())

# Step 2 — Then fill
numeric_cols = csv_1.select_dtypes(include="number").columns
for col in numeric_cols:
    csv_1[col] = csv_1[col].fillna(csv_1[col].median())

text_cols = csv_1.select_dtypes(include=["object", "string"]).columns
for col in text_cols:
    csv_1[col] = csv_1[col].fillna("Not Available")

# Step 3 — Then print AFTER filling 
print(f"Total missing values after filling: {csv_1.isnull().sum().sum()}")

Missing values per column:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64
Total missing values after filling: 0

In [87]:
filtered_csv_1 = csv_1[csv_1["rating"] > 4]
print(f"\nHigh-rated products (rating > 4): {len(filtered_csv_1)} records")
print(filtered_csv_1.head())

High-rated products (rating > 4): 533 records
   product_id           title                         product_description  \
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe
5    17198778             H&M  Beige & Tan Solid Stoneware Soap Dispenser

   rating  ratings_count  initial_price  discount  final_price currency  \
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR
5     4.5             42           1399      56.0  "₹1,399.00"      INR

                                              images  ...  \
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...
5  http://assets.myntassets.com/assets/images/171...  ...

                                     amount_of_stars what_customers_said  \
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...       Not Available
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...       Not Available
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...       Not Available
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...       Not Available
5  {"1_star":2,"2_stars":2,"3_stars":0,"4_stars":...       Not Available

                                        seller_name  \
1                                     Not Available
2                                     Not Available
3                                     Not Available
4                                     Not Available
5  H &███Hen███ & █████████eta█████████████████████

                                               sizes  \
1                               [{"size":"Onesize"}]
2                                     [{"size":"S"}]
3                               [{"size":"Onesize"}]
4  [{"size":"M","value":"45.0in","value_name":"Fr...
5                               [{"size":"Onesize"}]

                                              videos  \
1                              ["rw-9136281_cae700"]
2  ["https://videos.myntassets.com/assets/videos/...
3  ["https://videos.myntassets.com/assets/videos/...
4                                      Not Available
5                                      Not Available

                                  seller_information  \
1                                      Not Available
2                                      Not Available
3                                      Not Available
4                                      Not Available
5  Pra███yat███fra█████████PVT███████████████████...

                                    variations  \
1                                      [{},{}]
2                          [{},{},{},{},{},{}]
3                                Not Available
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
5                                      [{},{}]

                                          best_offer  \
1                                                 {}
2                                                 {}
3                                                 {}
4                                                 {}
5  {"applicable_on":"Orders above Rs. 1499 (only ...

                                         more_offers              category
1  [{"offer_name":"10% Instant Discount on Citi C...             backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...             backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...             backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...             bath-robe
5  [{"offer_name":"10% Instant Discount on IndusI...  bathroom-accessories

[5 rows x 24 columns]

In [88]:
csv_1[["title", "rating"]].head()

            title  rating
0     Lino Perros     3.8
1  Tommy Hilfiger     4.5
2           Lavie     4.4
3          F Gear     4.4
4       MYTRIDENT     4.7

In [89]:
print(f"\nDuplicate rows found: {csv_1.duplicated().sum()}")
csv_1 = csv_1.drop_duplicates()
csv_1 = csv_1.reset_index(drop=True)
print(f"Duplicates after removal: {csv_1.duplicated().sum()}")

Duplicate rows found: 0
Duplicates after removal: 0

In [90]:
csv_1["final_price"] = (
    csv_1["final_price"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False)
    .astype(float)
)

In [91]:
csv_1["quantity"] = 1

In [92]:
csv_1["total_amount"] = csv_1["final_price"] * csv_1["quantity"]

In [93]:
csv_1[["final_price", "quantity", "total_amount"]].head()

   final_price  quantity  total_amount
0       3995.0         1        3995.0
1       2899.0         1        2899.0
2       2999.0         1        2999.0
3       1675.0         1        1675.0
4       2899.0         1        2899.0

In [94]:
csv_1.to_csv("cleaned_dataset.csv", index=False)
print("\nCleaned dataset saved as 'cleaned_dataset.csv'")
print("Final Shape: {csv_1.shape[0]} rows x {csv_1.shape[1]} columns")

Cleaned dataset saved as 'cleaned_dataset.csv'
Final Shape: {csv_1.shape[0]} rows x {csv_1.shape[1]} columns

## 📝 Summary

**Dataset:** Combined_dataset.csv (Ecommerce Shopping Data)

| | Original | Cleaned |
|---|---|---|
| Rows | 1000 | 1000 |
| Columns | 24 | 26 |

**Changes Made:**
- ✅ Missing values filled (numeric → median, text → 'Not Available')
- ✅ Duplicate check performed → 0 found, dataset was already unique
- ✅ Filtered high-rated products (rating > 4)
- ✅ Added `quantity` column (default = 1)
- ✅ Added `total_amount` = final_price × quantity
- ✅ Saved as `cleaned_dataset.csv`